sound: soc: msm: Fix in-tree compilation
In-tree compilation for sound/soc/msm/qdsp6v2/rtac.c was hitting
this error:

sound/soc/msm/qdsp6v2/rtac.c:29:21: fatal error: q6voice.h: No such
file or directory
 #include <q6voice.h>

This was due to using <> instead of "" style include.

Signed-off-by: Michal Chvíla <electrydev@gmail.com>